### ISSUE TITLE
No link to student-instructions-2.md

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/turing-test-lessons#5]
`Lesson-1/lesson-plan-1.md` contains a link to `student-instructions-1.md` (good), but `Lesson-2/lesson-plan-2.md` doesn't contain a link to `student-instructions-2.md` (bad) - neither does any other page.

(And just a quick note for the sake of consistency - `Lesson-3` doesn't contain a `student-instructions-3.md` file)

**Comment by MissPhilbin** [comment]
Some lessons require a student worksheet and others do not. They are not there for consistency, rather if a handout is needed. This is a teacher thing :) 

Students instructions 2 now linked in lesson plan but not required for the new template.
