### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/turing-test-lessons#7]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md
- [x] lesson.md
- [x] ks.md

**Comment by lauraclay** [comment]
Lesson folders need capitalisation removed.

**Comment by bennuttall** [comment]
Lesson folders now ok ^

**Comment by bennuttall** [comment]
[learn.md](https://github.com/raspberrypilearning/turing-test-lessons/blob/master/learn.md) is empty

**Comment by MissPhilbin** [comment]
Copied and pasted text from readme.md.
